### ISSUE TITLE
NullReferenceException in scenario with branches & Ldelem

### ISSUE THREAD

**Issue by den-mentiei** [skbkontur/gremit#23]
Hello!

The following code leads to a crash:
```cs
                using (var il = new GroboIL(reset))
                {
                    var index = il.DeclareLocal(typeof(int));
                    
                    il.Ldc_I4(0);
                    il.Stloc(index);
                    
                    var start = il.DefineLabel("start");
                    var compare = il.DefineLabel("compare");
                    
                    il.Br(compare);
                    il.MarkLabel(start);
                    il.Ldarg(0);
                    il.Ldfld(elements);
                    il.Ldloc(index);
                    il.Ldelem(OurElementType); // OurElementType is a reference type.
                    
                    il.Ldloc(index);
                    il.Ldc_I4(1);
                    il.Add();
                    il.Stloc(index);
                    
                    il.MarkLabel(compare);
                    il.Ldloc(index);
                    il.Ldarg(0);
                    il.Ldfld(machines);
                    il.Ldlen();
                    il.Conv<int>();
                    il.Blt(start, false); // FAIL HERE
                    
                    il.Ret();
                }
```

It fails with:
```
   at GrEmit.StackMutators.LdelemStackMutator.Mutate(GroboIL il, ILInstructionParameter parameter, EvaluationStack& stack) in C:\projects\gremit\GrEmit\StackMutators\LdelemStackMutator.cs:line 11
   at GrEmit.StackMutatorCollection.Mutate(OpCode opCode, GroboIL il, ILInstructionParameter parameter, EvaluationStack& stack) in C:\projects\gremit\GrEmit\StackMutatorCollection.cs:line 18
   at GrEmit.StackMutator.Propogate(GroboIL il, Int32 lineNumber, EvaluationStack stack) in C:\projects\gremit\GrEmit\StackMutator.cs:line 336
   at GrEmit.StackMutator.SaveOrCheck(GroboIL il, EvaluationStack stack, Label label) in C:\projects\gremit\GrEmit\StackMutator.cs:line 145
   at GrEmit.StackMutators.BinOpStackMutator.Mutate(GroboIL il, ILInstructionParameter parameter, EvaluationStack& stack) in C:\projects\gremit\GrEmit\StackMutators\BinOpStackMutator.cs:line 24
   at GrEmit.StackMutatorCollection.Mutate(OpCode opCode, GroboIL il, ILInstructionParameter parameter, EvaluationStack& stack) in C:\projects\gremit\GrEmit\StackMutatorCollection.cs:line 18
   at GrEmit.GroboIL.Emit(OpCode opCode, Label label) in C:\projects\gremit\GrEmit\GroboIL.cs:line 2256
   at GrEmit.GroboIL.Blt(Label label, Boolean unsigned) in C:\projects\gremit\GrEmit\GroboIL.cs:line 574
```

Some initial debugging shows, that:
- `il.MarkLabel(start)` resets `GroboIL.stack` to `null`
- `il.LdElem` doesn't mutate stack (as it is `null` now), so its parameter (with element type) is thrown away
- ...
- `il.Blt(start, false)` starts to recover the stack for the jump location and it goes through recorded instructions accessing corresponding parameters
- we get NRE in `LdelemStackMutator` as `ldelem` parameter is not available (`== null`).

**Comment by den-mentiei** [comment]
https://github.com/skbkontur/gremit/blob/f666e8fd2b3b7594e80ee8920e2e30133ffe0a7e/GrEmit/GroboIL.cs#L2134
It might be changed to `var lineNumber = ilCode.Append(opCode, parameter, new EmptyILInstructionComment());`
to solve the issue?

**Comment by Anton92nd** [comment]
https://www.nuget.org/packages/GrEmit/3.3.18
